siteName: Madras
description: A magical textbook
domain: madras.id

privacyURL: /policies
banner: (c) Madras
locales: [en, ar, cn, de, es, fr, hi, hr, it, ja, pt, ro, ru, sv, tr, vi]

search:
  enabled: false

footer:
  rows:
    - links:
        - title: Follow us on Instagram
          url: https://www.instagram.com/madras.id/
        - title: Give us your suggestion
          url: https://forms.gle/maUSfWPWCmgoz5RM9
  copyright: © Madras, 2022

social:
  facebook: {}
  twitter: {}

courses:
  showLocked: true
  revealAll: false
  audio: true

tutor:
  enabled: true

accounts:
  enabled: true

  # Minimum age allowed for users
  minAge: 11

  # Required privacy information
  privacyPolicy: https://madras.id/policies
  termsOfUse: https://madras.id/terms
  address: Jalan Asem Kranji, Depok, Sleman, D.I. Yogyakarta

  # Support email that users can contact
  supportEmail: halo@madras.id

  # Email address that receives CRON job notification emails (optional)
  cronNotificationsEmail: halo@madras.id

  # Sendgrid API key. Should use place holder
  sendgridKey: 12345 //

  # MongoDB URL (optional). Should use place holder
  mongodb: mongodb+srv://madras:YJXbvfFRzIk5Vpfk@clustermadras0.z11yf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
